### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by sewil** [heyman333/react-native-responsive-fontSize#12]

**Comment by heyman333** [comment]
I'm sorry.
But there is no concrete reason to fix the problem.

Write a description of the bug, even if it is not detailed.

**Comment by Multi-Thinker** [comment]
+1 same, adding some percentage. let say RFPercentage which works perfect on 720, doesn't work on 1080, doesn't work on 480. the whole purpose of this library was to provide "responsiveness" it is still "static/fixed". 

code can be tested like this
``<Text style={{fontSize:RFPercentage(1.5)}}>Hello there, is is one heck of a long line</Text>``

**Comment by heyman333** [comment]
@Multi-Thinker Thank you for your review. I'll check it asap
