### ISSUE TITLE
RFValue the second argument not optional!

### ISSUE THREAD

**Issue by jon-moreira** [heyman333/react-native-responsive-fontSize#20]
According your documentation [https://github.com/heyman333/react-native-responsive-fontSize#methods](url) the second argument of RFValue is optional. But checking your code it's not  optional! [https://github.com/heyman333/react-native-responsive-fontSize/blob/master/index.js](url) 

```
// guideline height for standard 5" device screen is 680
export function RFValue(fontSize, standardScreenHeight = 680) {
  const heightPercent = (fontSize * deviceHeight) / standardScreenHeight;
  return Math.round(heightPercent);
}
```

**Comment by heyman333** [comment]
@expouic
fixed in #18
Please update version

Thank you
