### ISSUE TITLE
font gets too big on iPhone 11

### ISSUE THREAD

**Issue by VladRDV** [heyman333/react-native-responsive-fontSize#29]
noticed a strange behavior on iPhone 11, fontSize just explodes on that one 

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React from 'react';
import { SafeAreaView, StyleSheet, ScrollView, View, Text, StatusBar } from 'react-native';

import { Header, LearnMoreLinks, Colors, DebugInstructions, ReloadInstructions } from 'react-native/Libraries/NewAppScreen';
import { RFPercentage, RFValue } from 'react-native-responsive-fontsize';

const App = () => {
	return (
		<SafeAreaView style={{ flex: 1 }}>
			<StatusBar barStyle="dark-content" />
			<ScrollView contentInsetAdjustmentBehavior="automatic" style={styles.scrollView}>
				<Header />
				{global.HermesInternal == null ? null : (
					<View style={styles.engine}>
						<Text style={styles.footer}>Engine: Hermes</Text>
					</View>
				)}
				<View style={styles.body}>
					<View style={styles.sectionContainer}>
						<Text style={styles.sectionTitle}>Step One</Text>
						<Text style={styles.sectionDescription}>
							Edit <Text style={styles.highlight}>App.js</Text> to change this screen and then come back to see your edits.
						</Text>
					</View>
					<View style={styles.sectionContainer}>
						<Text style={styles.sectionTitle}>See Your Changes</Text>
						<Text style={styles.sectionDescription}>
							<ReloadInstructions />
						</Text>
					</View>
					<View style={styles.sectionContainer}>
						<Text style={styles.sectionTitle}>Debug</Text>
						<Text style={styles.sectionDescription}>
							<DebugInstructions />
						</Text>
					</View>
					<View style={styles.sectionContainer}>
						<Text style={styles.sectionTitle}>Learn More</Text>
						<Text style={styles.sectionDescription}>Read the docs to discover what to do next:</Text>
					</View>
					<LearnMoreLinks />
				</View>
			</ScrollView>
		</SafeAreaView>
	);
};

const styles = StyleSheet.create({
	scrollView: {
		backgroundColor: Colors.lighter
	},
	engine: {
		position: 'absolute',
		right: 0
	},
	body: {
		backgroundColor: Colors.white
	},
	sectionContainer: {
		marginTop: 32,
		paddingHorizontal: 24
	},
	sectionTitle: {
		fontSize: RFValue(24), // 5%
		fontWeight: '600',
		color: Colors.black
	},
	sectionDescription: {
		marginTop: 8,
		fontSize: RFPercentage(4), // 18
		fontWeight: '400',
		color: Colors.dark
	},
	highlight: {
		fontWeight: '700'
	},
	footer: {
		color: Colors.dark,
		fontSize: RFPercentage(3), // 12
		fontWeight: '600',
		padding: 4,
		paddingRight: 12,
		textAlign: 'right'
	}
});

export default App;

```

<img width="1134" alt="Screenshot 2020-03-26 at 01 49 04" src="https://user-images.githubusercontent.com/19750070/77599352-afe82380-6f04-11ea-888a-ffb35acc0191.png">

**Comment by heyman333** [comment]
@VladRDV Thank you for your reporting!
I will check it and comment on your report asap

**Comment by heyman333** [comment]
<img width="699" alt="스크린샷 2020-03-27 오전 1 50 55" src="https://user-images.githubusercontent.com/22214150/77673429-80511e00-6fcd-11ea-8cea-e80f45e4e236.png">
<img width="680" alt="스크린샷 2020-03-27 오전 1 51 22" src="https://user-images.githubusercontent.com/22214150/77673434-81824b00-6fcd-11ea-9f45-d8272f70491e.png">


After instant testing, it seems that there is no problem.

If you still have problems installing the latest version,
Can you explain the `Steps to Reproduce`?

**Comment by VladRDV** [comment]
@heyman333, thanks for quick responce 
I was just following [the instructions from readme](https://github.com/heyman333/react-native-responsive-fontSize).

Here is the weird thing.  The problem with font size on iPhone 11 fixed itself after I deleted and recreated  iPhone 11 simulator in `Hardware > Device > Manage Devices > Simulators`

<img width="1130" alt="rnrfs_screenshor" src="https://user-images.githubusercontent.com/19750070/77704554-a078e100-6fbd-11ea-86ea-b1083667a310.png">

fontSize on iPhone 11 (on the right) now behaves normally

I'll run some tests on real devices, once I get my hands on them, but I think that problem was with the simulator.

Maybe there should be a 'Troubleshooting' section in readme for such things?

**Comment by heyman333** [comment]
@VladRDV Thank you. I will make up `README` according to your suggestion👍

**Comment by RigottiG** [comment]
Same issue here, any updates ?
