### ISSUE TITLE
Suggestion: Can RF take fontSize as a parameter?

### ISSUE THREAD

**Issue by jamesmcn1** [heyman333/react-native-responsive-fontSize#3]
Hey guys, like the idea of the library.

Small suggestion:
It would be great if the RF function took in a fontsize as a parameter rather than a percentage, as it will be alot easier to install this library and utilise the RF function if I can simply wrap all my existing fontSize in the RF function.

I can try to make a PR for this if you're interested?

**Comment by heyman333** [comment]
hello @jamesmcn1
I am really sorry for my belated reply and thank you for your suggestion.

I thought your opinion is really good. 
What do you think of offering two options to use percentage or existing font-sizes?

e.g `RFPercentage(3.5)`,`RFValue(16)`

If you send me a `PR`, I will merge it gladly 
thanks.

**Comment by heyman333** [comment]
ping @jamesmcn1 
are you in progress?

if you are not interested in, It looks good to close the issue.

**Comment by jamesmcn1** [comment]
Hey @heyman333 sorry i have been super busy recently! Will get around to this at some point soon. :)

**Comment by heyman333** [comment]
This issue was performed #4
