### ISSUE TITLE
Auto adjust fontsize not working on different screen size

### ISSUE THREAD

**Issue by nikitashaha104** [heyman333/react-native-responsive-fontSize#36]
I have used this lib in my project. I want text in one line need to auto adjust font on the basis of screen size.
![fontsize](https://user-images.githubusercontent.com/68632943/93602088-c072e580-f9df-11ea-9209-5c510df8541d.png)

const style = Stylesheet.create({
textStyle: {
    fontFamily: 'ClearSans-Medium',
    fontSize: RFPercentage(2),
  }
});

**Comment by HigorAlves** [comment]
Please assing this to me!
