### ISSUE TITLE
Indeed, none of these files exist

### ISSUE THREAD

**Issue by mikepc** [heyman333/react-native-responsive-fontSize#9]
error: bundling failed: Error: While trying to resolve module `react-native-responsive-fontsize` from file `/Users/michael/owlbrite/eventlocal/src/Modules/MapScreen/styles.js`, the package `/Users/michael/owlbrite/eventlocal/node_modules/react-native-responsive-fontsize/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/michael/owlbrite/eventlocal/node_modules/react-native-responsive-fontsize/index.ts`. Indeed, none of these files exist:

  * `/Users/michael/owlbrite/eventlocal/node_modules/react-native-responsive-fontsize/index.ts(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/michael/owlbrite/eventlocal/node_modules/react-native-responsive-fontsize/index.ts/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/michael/owlbrite/eventlocal/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:108:15)
    at DependencyGraph.resolveDependency (/Users/michael/owlbrite/eventlocal/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at new Promise (<anonymous>)
    at /Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
    at /Users/michael/owlbrite/eventlocal/node_modules/metro/src/DeltaBundler/traverseDependencies.js:237:9

**Comment by heyman333** [comment]
@mikepc Thank you for your feedback!
Actually I could't test my module enough

I will fix and repulish it ASAP

**Comment by heyman333** [comment]
@mikepc

I tested the module and I could not figure out what the problem was.
my test env is like as below

```
react-native: 0.57.7
vscode:  1.30.0(1.30.0)
```

if you want to make it up. Don't hesitate to make new pullrequest
